### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by furbaez** [dhoer/gitlab-secrets#4]
How can I add a pattern to scan for password or something like 

-----BEGIN CERTIFICATE-----
wYDVR0fBDwwOjA4oDagNIYyaHR0cDovL3JhcGlkc3NsLWNybC5n
ZW90cnVzdC5jb20vY3Jscy9yYXBpZHNzbC5jcmwwHQYDVR0OBBYEFA8nu+rbiNqg
DYmhNE0IgXx6XRHiMAwGA1UdEwEB/wQCMAAwSQYIKwYBBQUHAQEEPTA7MDkGCCsG
gOYD8kmKOsxLRWeZo6Tn8
-----END CERTIFICATE-----

**Comment by dhoer** [comment]
Look at https://github.com/dhoer/gitlab-secrets/blob/master/git-hooks/.gitconfig#L8   

Add a pattern something like ‘^——-BEGIN.*’. Don’t add the cert word because that be different, e.g., ——-BEGIN RSA CERTIFICATE.

**Comment by furbaez** [comment]
Ok, inside the server where do you set that up I log in to the container to see where this is setup but I can't figure this out.  I will be implementing this on my gitlab server running on a EC2

is this regular expression? https://github.com/dhoer/gitlab-secrets/blob/master/git-hooks/.gitconfig#L11
I wanted to have a pattern to look at passwords like https://www.ocpsoft.org/tutorials/regular-expressions/password-regular-expression/  is that possible?
